### ISSUE TITLE
Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory

### ISSUE THREAD

**Issue by RobinJ1995** [codywd/NetGUI#15]
Installed NetGUI on Arch, but can't actually seem to get it to start.
Might be missing a dependency, so more of a packaging bug?

[robin@pingwing examples]$ sudo netgui -v
Your netgui version is 0.65.
[robin@pingwing examples]$ sudo netgui
Please wait! Now Scanning.
interface:: up: wlp5s0
Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory
Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory
Done Scanning!

**Comment by bphd** [comment]
What about 

Failed to connect to non-global ctrl-ifname: (nil) error: Success
