### ISSUE TITLE
ctrl_iface exists and seems to be in use - cannot override it

### ISSUE THREAD

**Issue by codywd** [codywd/NetGUI#22]
```
ctrl_iface exists and seems to be in use - cannot override it
Delete '/run/wpa_supplicant/wlp9s0' manually if it is not used anymore
Failed to initialize control interface '/run/wpa_supplicant'.
You may have another wpa_supplicant process already running or the file was
left by an unclean termination of wpa_supplicant in which case you will need
to manually remove this file before starting wpa_supplicant again.
```

This error message appears every time there is a scan that runs. This is related to wpa_cli and wpa_supplicant, and this bug needs to be worked out.

Potential options:
1. `wpa_cli terminate` - This command automatically terminates the currently running wpa_supplicant.
2. `os.remove(wpa_supplicant_file)` - This command will forcibly remove the interface lock. Not preferable.
3. ???

Marked as Priority // 1 HIGH and not Priority // 0 HIGHEST because it does not break the program. It functions perfectly, with a failure with what seems to be once in a blue moon.

**Comment by faker09** [comment]
i just want to connect two wifi ,can your help me
