### ISSUE TITLE
No such file or directory: 'Successfully initalized wpa_supplicant

### ISSUE THREAD

**Issue by Timidger** [codywd/NetGUI#46]
When trying out the program for the first time, I was greeted with this weird looking error message: 

![2015-04-20-171325_1276x777_scrot](https://cloud.githubusercontent.com/assets/3515754/7240686/f32cdfca-e780-11e4-895e-b41672a2b3da.png)

I'm using Arch, 3.18.6-1 kernel (64-bit). The only weird thing with my WiFi is that instead of using the default WiFi card, I'm using a USB dongle (because the card fails consistently):
(`Edimax Technology Co., Ltd EW-7811Un 802.11n Wireless Adapter [Realtek RTL8188CUS]`)

**Comment by codywd** [comment]
What is the name your wireless adapter was assigned? Can you check what NetGUI detected it as? (/var/lib/netgui/interface.cfg)

I know this is far late, so you may not even be using NetGUI anymore, but I hope I can still get this fixed. What is weird is what it detected the directory name as "Successfully initialized wpa_supplicant"

**Comment by Timidger** [comment]
Unfortunately, I have since replaced the WiFi card in that laptop and lost the WiFi dongle so I can no longer report much on the subject. However, I do remember the interface name was enp0s25 (mostly because I had to type it in so much to  mess with the dongle). Hopefully the issue won't crop up again for anyone else. Feel free to close this, I no longer have the issue.

**Comment by codywd** [comment]
Okay, thanks for the update.
